---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: :verify_none

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[mock-data::default]
      - recipe[chefy-server::default]
    attributes:
      demo:
        admin-user: 'vagrant'
